# версия синтаксиса
version: '3'

# в этом блоке мы описываем контейнеры, которые будут запускаться
services:
  # контейнеры с nginx
  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    image: myapp/nginx
    container_name: webserver2
    # проброс портов
    ports:
      - "80:80"
    volumes:
      - ./code:/data/mysite.local
    networks:
      - app-network

  # Контайнер с PHP-FPM, назовем его app
  app:
    # Если нет секции build, тосистема будет искать образ в репозитории
    build:
      context: ./fpm
      dockerfile: Dockerfile
    image: myapp/php # имя будущего образа
    container_name: app2 # имя контейнреа после запуска
    volumes:
      - ./code:/data/mysite.local
    # Мы можем создать для контейнера внутренню сеть
    networks:
      - app-network

   #Контейнер с PHP-FPM, назовём его app
  cli:
    # Если нет секции build, то система будет искать образ в репозиториях
    build:
      context: ./cli
      dockerfile: Dockerfile
    image: myapp/php-cli # имя будущего образа
    container_name: cli # имя контейнера после запуска
    volumes:
       - ./code:/data/mysite.local
    # мы можем создать для контейнеров внутреннюю сеть
    networks:
      - app-network

# Docker Networks
networks:
  app-network:
    driver: bridge